soverenio/helm-charts

charts/soveren-agent/Chart.yaml
charts/soveren-agent/values.yaml

22.10.3- new Interceptor and Digger

New release 22.10.3

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/values.yaml

release 22.11.1

---

charts/soveren-agent/values.yaml

Add default configuration to allow all namespaces. Empty list still works but new version is more explicit.

SMAT-1306: Exclude namespaces

---

charts/soveren-agent/templates/detection-tool-cm.yaml
charts/soveren-agent/values.yaml

Rename env var for detection-tool log level.

SMAT-1399: Rename detection-tool log level env var

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/values.yaml

Release 23.1.1

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/templates/detection-tool-service.yaml
charts/soveren-agent/templates/prometheus-agent-cm.yaml
charts/soveren-agent/values.yaml

Digger: [v0.19.0]
Interceptor: [v0.18.1]
Detection Tool: [v1.6.2]

Release 23.3.1

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/templates/interceptor-cm.yaml
charts/soveren-agent/values.yaml

also remove unneeded and unused options namespacelocal

NOISSUE: add configuration options for envoy port

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/templates/detection-tool-cm.yaml
charts/soveren-agent/templates/detection-tool-deployment.yaml
charts/soveren-agent/templates/digger-deployment.yaml
charts/soveren-agent/templates/digger-rbac.yaml
charts/soveren-agent/templates/kafka-deployment.yaml
charts/soveren-agent/templates/prometheus-agent-cm.yaml
charts/soveren-agent/values.yaml

appVersion: "23.4.2"
Boxy release v0.22.0

Release 23.4.2

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/values.yaml

Downgrade interceptor to v0.20.2

Release 23.5.1

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/values.yaml

Release 23.6.1
Boxy: v0.24.0
Detection tool: v1.6.3

Release 23.6.1

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/values.yaml

Release 23.6.5 
Boxy: v0.24.4
Detection tool: v1.6.3

Release 23.6.5

---

charts/soveren-agent/templates/digger-cm.yaml
charts/soveren-agent/templates/kafka-deployment.yaml
charts/soveren-agent/values.yaml

В пару к https://github.com/soverenio/boxy/pull/443

SMAT-2373: Create logs topic in kafka and base config params

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/templates/detection-tool-cm.yaml
charts/soveren-agent/templates/detection-tool-deployment.yaml
charts/soveren-agent/values.yaml

Boxy: v0.25.2
DetectionTool: v2.2.4
chartVersion: 1.27.0

Release 23.8.2

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/templates/digger-cm.yaml
charts/soveren-agent/values.yaml

Boxy: v0.26.0
Detection tool: v2.4.1
chartVersion: 1.31.0

Release 23.9.2

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/templates/digger-cm.yaml
charts/soveren-agent/values.yaml

version: 1.33.0
appVersion: "23.10.2"
boxy: v0.27.1
detectionTool: v2.6.1

Release 23.10.2

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/templates/detection-tool-deployment.yaml
charts/soveren-agent/values.yaml

Release 23.12.1
Boxy v0.29.0
Detection: 2.7.1

Release 23.12.1

---

charts/soveren-dar-sensor/Chart.yaml
charts/soveren-dar-sensor/templates/prometheus-agent-cm.yaml

Release 24.01.02 dar

---

charts/soveren-agent/Chart.yaml
charts/soveren-agent/values.yaml

New detecion tool version - fix external requests

Release 24.4.2-DIM

---

charts/soveren-agent/release-notes.md
charts/soveren-dar-sensor/release-notes.md

* DAR-24.7.2-DT
* DIM-24.7.1-hotfix

release-notes:

---

charts/soveren-agent/templates/kafka-deployment.yaml

Increase broker parameter max.message.bytes to 5Mb

SMAT-4235: Increase broker parameter max.message.bytes to 5Mb
